
failed_count := 0;

main :: ()
{
    println("Running tests...");
    
    // Examples
    {
        set_cd("../examples/");
        println("## EXAMPLES:");
        
        run_test("basics.yov", "", 0);
        run_test("default_definitions.yov", "", 0);
        run_test("errors.yov", "", 0);
        run_test("external_calls.yov", "", 0);
        run_test("file_system.yov", "", 0);
        run_test("script_args.yov", "-foo=A", 0);
        
        println("");
    }
    
    // Tests
    {
        set_cd("../tests/");
        println("## TESTS:");
        
        run_test("basics.yov", "", 0);
        run_test("expressions.yov", "", 0);
        run_test("references.yov", "", 0);
        //run_test("any.yov", "", 0);
        
        println("");
    }
    
    println("Failed: {failed_count}");
    exit(failed_count);
}

run_test :: (name: String, args: String, expected_code: Int)
{
    calls.redirect_stdout = RedirectStdout.Script;
    out, res := call_script(name, args, "-no_user");
    if (res.code != expected_code) {
        failed_count += 1;
        println("-> Test failed: {name}");
        println(out.stdout);
    }
    else {
        println("Test succeded: {name}");
    }
}